### ISSUE TITLE
installing openLISEM (incl. patched Qwt) from source on Linux

### ISSUE THREAD

**Issue by boegel** [vjetten/openlisem#1]
I'm trying to build openLISEM 6.848 from source on Linux.

I was first trying to use the standard Qwt v6.2.0 as dependency for this, but compiler errors for missing `setAxesCount` made me realize that a custom `Qwt` is required (which is made available via https://github.com/vjetten/openlisem/releases/download/openLisem/qwt-6.1-ma.zip).

Trying to build the custom Qwt from source quickly leads to problems due to hardcoded Windows-isms however:

```
/bin/sh: C:Qtmsys64mingw64binqmake.exe: command not found
```

Are detailed step-by-step instructions available somewhere on how to get openLISEM built from source on Linux?

**Comment by vjetten** [comment]
no I am afraid not... so I guess you have to hardcode some stuff. I don't know linux myself very wellI. f you find a solution pkease share

**Comment by vjetten** [comment]
this is the branch source code for the double axis version of QWT:
https://sourceforge.net/p/qwt/code/HEAD/tree/branches/qwt-6.1-multiaxes/
maybe you can compile this under linux?

**Comment by vjetten** [comment]
btw: in the repository is a file: "ubuntu compile.txt"

**Comment by boegel** [comment]
Eventually I managed to get `openLISEM` installed using the `multiaxes` branch of Qwt 6.1 .

More details are available in https://github.com/vscentrum/vsc-software-stack/blob/23659d1c05874b841a216ea864b838e794777dde/25-openLISEM/openLISEM.eb, which is an easyconfig file for [EasyBuild](https://easybuild.io) which automates the whole installation process.

We're still running into some runtime issues. Some are just annoying, like openLISEM requiring a desktop environment and failing to run in a headless environment, and requiring write access to the installation directory to create a file named `openlisemtmp.run`, but others are an actual blocker, primarily a `Segmentation fault` when running a test case, which may point to a bug in the code...

**Comment by vjetten** [comment]
Hi

Thanks for the adjustments. The desktop environment is a Qt windows thing if that is what you mean, don’t know what it needs to be in Linux. Easybuild seems interesting, not sure if I will use it. 

 

I don’t use a fixed location for openlisem, users tend to copy it near their project. So that’s why the temp runfile is with the software. But prob. There are better locations such as a temp folder.

 

Somebody found a segmentation error in the function MapTotal. That might point to two causes:

double TWorld::MapTotal(cTMap &M)

{

    double total = 0;

    #pragma omp parallel for reduction(+:total) num_threads(userCores)

    FOR_ROW_COL_MV_L {

       total = total + M.Drc;

    }}

    return (total);

}

 

Maybe comment out the line

#pragma omp parallel for reduction(+:total) num_threads(userCores)

To see if the problem is the paralelisation, 

 

Or make an extra check for a missing value:

 

 

double TWorld::MapTotal(cTMap &M)

{

    double total = 0;

    #pragma omp parallel for reduction(+:total) num_threads(userCores)

    FOR_ROW_COL_MV_L {

       if (!pcr::isMV(M->Drc)

               total = total + M.Drc;

    }}

    return (total);

}

 

 

 

Best

Victor
